// Emoji 轉換工具模組
export const emojiMap = {
  // 表情符號
  ':smile:': '😊',
  ':grinning:': '😀',
  ':joy:': '😂',
  ':laughing:': '😆',
  ':wink:': '😉',
  ':blush:': '😊',
  ':heart_eyes:': '😍',
  ':kissing_heart:': '😘',
  ':relaxed:': '☺️',
  ':satisfied:': '😆',
  ':grin:': '😁',
  ':winking_face:': '😉',
  ':stuck_out_tongue:': '😛',
  ':stuck_out_tongue_winking_eye:': '😜',
  ':stuck_out_tongue_closed_eyes:': '😝',
  ':disappointed:': '😞',
  ':worried:': '😟',
  ':angry:': '😠',
  ':rage:': '😡',
  ':cry:': '😢',
  ':persevere:': '😣',
  ':triumph:': '😤',
  ':disappointed_relieved:': '😥',
  ':frowning:': '😦',
  ':anguished:': '😧',
  ':fearful:': '😨',
  ':weary:': '😩',
  ':sleepy:': '😪',
  ':tired_face:': '😫',
  ':grimacing:': '😬',
  ':sob:': '😭',
  ':open_mouth:': '😮',
  ':hushed:': '😯',
  ':cold_sweat:': '😰',
  ':scream:': '😱',
  ':astonished:': '😲',
  ':flushed:': '😳',
  ':sleeping:': '😴',
  ':dizzy_face:': '😵',
  ':no_mouth:': '😶',
  ':mask:': '😷',
  
  // 手勢和符號
  ':thumbsup:': '👍',
  ':thumbsdown:': '👎',
  ':ok_hand:': '👌',
  ':punch:': '👊',
  ':fist:': '✊',
  ':v:': '✌️',
  ':wave:': '👋',
  ':hand:': '✋',
  ':raised_hand:': '✋',
  ':open_hands:': '👐',
  ':point_up:': '☝️',
  ':point_down:': '👇',
  ':point_left:': '👈',
  ':point_right:': '👉',
  ':raised_hands:': '🙌',
  ':pray:': '🙏',
  ':clap:': '👏',
  ':muscle:': '💪',
  
  // 心形和愛情
  ':heart:': '❤️',
  ':broken_heart:': '💔',
  ':two_hearts:': '💕',
  ':heartpulse:': '💗',
  ':heartbeat:': '💓',
  ':sparkling_heart:': '💖',
  ':cupid:': '💘',
  ':gift_heart:': '💝',
  ':heart_decoration:': '💟',
  ':purple_heart:': '💜',
  ':yellow_heart:': '💛',
  ':green_heart:': '💚',
  ':blue_heart:': '💙',
  
  // 符號和標誌
  ':star:': '⭐',
  ':star2:': '🌟',
  ':dizzy:': '💫',
  ':boom:': '💥',
  ':collision:': '💥',
  ':anger:': '💢',
  ':sweat_drops:': '💦',
  ':droplet:': '💧',
  ':zzz:': '💤',
  ':dash:': '💨',
  ':fire:': '🔥',
  ':rocket:': '🚀',
  ':airplane:': '✈️',
  ':car:': '🚗',
  ':taxi:': '🚕',
  ':bus:': '🚌',
  ':train:': '🚂',
  ':bike:': '🚲',
  ':ship:': '🚢',
  ':boat:': '⛵',
  ':speedboat:': '🚤',
  ':truck:': '🚚',
  ':ambulance:': '🚑',
  ':police_car:': '🚓',
  ':fire_engine:': '🚒',
  
  // 警告和信息
  ':warning:': '⚠️',
  ':exclamation:': '❗',
  ':question:': '❓',
  ':grey_exclamation:': '❕',
  ':grey_question:': '❔',
  ':bangbang:': '‼️',
  ':interrobang:': '⁉️',
  ':x:': '❌',
  ':heavy_multiplication_x:': '✖️',
  ':heavy_plus_sign:': '➕',
  ':heavy_minus_sign:': '➖',
  ':heavy_division_sign:': '➗',
  ':white_check_mark:': '✅',
  ':ballot_box_with_check:': '☑️',
  ':radio_button:': '🔘',
  ':link:': '🔗',
  ':curly_loop:': '➰',
  ':wavy_dash:': '〰️',
  ':part_alternation_mark:': '〽️',
  ':trident:': '🔱',
  
  // 信息和提示
  ':info:': 'ℹ️',
  ':information_source:': 'ℹ️',
  ':check:': '✅',
  ':heavy_check_mark:': '✔️',
  ':cross:': '❌',
  ':negative_squared_cross_mark:': '❎',
  
  // 技術和工具
  ':computer:': '💻',
  ':laptop:': '💻',
  ':desktop_computer:': '🖥️',
  ':keyboard:': '⌨️',
  ':computer_mouse:': '🖱️',
  ':trackball:': '🖲️',
  ':joystick:': '🕹️',
  ':compression:': '🗜️',
  ':minidisc:': '💽',
  ':floppy_disk:': '💾',
  ':cd:': '💿',
  ':dvd:': '📀',
  ':vhs:': '📼',
  ':camera:': '📷',
  ':camera_flash:': '📸',
  ':video_camera:': '📹',
  ':movie_camera:': '🎥',
  ':film_projector:': '📽️',
  ':film_strip:': '🎞️',
  ':telephone_receiver:': '📞',
  ':phone:': '☎️',
  ':telephone:': '☎️',
  ':pager:': '📟',
  ':fax:': '📠',
  ':tv:': '📺',
  ':radio:': '📻',
  ':studio_microphone:': '🎙️',
  ':level_slider:': '🎚️',
  ':control_knobs:': '🎛️',
  ':stopwatch:': '⏱️',
  ':timer_clock:': '⏲️',
  ':alarm_clock:': '⏰',
  ':mantelpiece_clock:': '🕰️',
  ':hourglass_done:': '⌛',
  ':hourglass:': '⏳',
  ':satellite:': '📡',
  ':battery:': '🔋',
  ':electric_plug:': '🔌',
  ':bulb:': '💡',
  ':flashlight:': '🔦',
  ':candle:': '🕯️',
  ':wastebasket:': '🗑️',
  ':oil_drum:': '🛢️',
  ':money_with_wings:': '💸',
  ':dollar:': '💲',
  ':yen:': '💴',
  ':euro:': '💶',
  ':pound:': '💷',
  ':moneybag:': '💰',
  ':credit_card:': '💳',
  ':gem:': '💎',
  ':balance_scale:': '⚖️',
  ':wrench:': '🔧',
  ':hammer:': '🔨',
  ':hammer_and_pick:': '⚒️',
  ':hammer_and_wrench:': '🛠️',
  ':pick:': '⛏️',
  ':nut_and_bolt:': '🔩',
  ':gear:': '⚙️',
  ':brick:': '🧱',
  ':chains:': '⛓️',
  ':magnet:': '🧲',
  ':gun:': '🔫',
  ':bomb:': '💣',
  ':firecracker:': '🧨',
  ':hocho:': '🔪',
  ':dagger:': '🗡️',
  ':crossed_swords:': '⚔️',
  ':shield:': '🛡️',
  ':smoking:': '🚬',
  ':skull_and_crossbones:': '☠️',
  ':coffin:': '⚰️',
  ':funeral_urn:': '⚱️',
  ':amphora:': '🏺',
  
  // 辦公和學習
  ':briefcase:': '💼',
  ':handbag:': '👜',
  ':pouch:': '👝',
  ':purse:': '👛',
  ':eyeglasses:': '👓',
  ':dark_sunglasses:': '🕶️',
  ':closed_umbrella:': '🌂',
  ':umbrella:': '☂️',
  ':necktie:': '👔',
  ':shirt:': '👕',
  ':jeans:': '👖',
  ':scarf:': '🧣',
  ':gloves:': '🧤',
  ':coat:': '🧥',
  ':socks:': '🧦',
  ':dress:': '👗',
  ':kimono:': '👘',
  ':bikini:': '👙',
  ':womans_clothes:': '👚',
  ':school_satchel:': '🎒',
  ':mans_shoe:': '👞',
  ':athletic_shoe:': '👟',
  ':high_heel:': '👠',
  ':sandal:': '👡',
  ':boot:': '👢',
  ':crown:': '👑',
  ':womans_hat:': '👒',
  ':tophat:': '🎩',
  ':mortar_board:': '🎓',
  ':billed_cap:': '🧢',
  ':helmet_with_white_cross:': '⛑️',
  ':prayer_beads:': '📿',
  ':lipstick:': '💄',
  ':ring:': '💍',
  
  // 食物和飲料
  ':apple:': '🍎',
  ':green_apple:': '🍏',
  ':pear:': '🍐',
  ':tangerine:': '🍊',
  ':lemon:': '🍋',
  ':banana:': '🍌',
  ':watermelon:': '🍉',
  ':grapes:': '🍇',
  ':strawberry:': '🍓',
  ':melon:': '🍈',
  ':cherries:': '🍒',
  ':peach:': '🍑',
  ':pineapple:': '🍍',
  ':coconut:': '🥥',
  ':kiwi_fruit:': '🥝',
  ':mango:': '🥭',
  ':avocado:': '🥑',
  ':broccoli:': '🥦',
  ':tomato:': '🍅',
  ':eggplant:': '🍆',
  ':cucumber:': '🥒',
  ':carrot:': '🥕',
  ':hot_pepper:': '🌶️',
  ':potato:': '🥔',
  ':sweet_potato:': '🍠',
  ':peanuts:': '🥜',
  ':honey_pot:': '🍯',
  ':croissant:': '🥐',
  ':bread:': '🍞',
  ':baguette_bread:': '🥖',
  ':bagel:': '🥯',
  ':pretzel:': '🥨',
  ':cheese:': '🧀',
  ':egg:': '🥚',
  ':bacon:': '🥓',
  ':steak:': '🥩',
  ':poultry_leg:': '🍗',
  ':meat_on_bone:': '🍖',
  ':hamburger:': '🍔',
  ':fries:': '🍟',
  ':pizza:': '🍕',
  ':hotdog:': '🌭',
  ':sandwich:': '🥪',
  ':taco:': '🌮',
  ':burrito:': '🌯',
  ':green_salad:': '🥗',
  ':shallow_pan_of_food:': '🥘',
  ':canned_food:': '🥫',
  ':spaghetti:': '🍝',
  ':ramen:': '🍜',
  ':stew:': '🍲',
  ':fish:': '🐟',
  ':shrimp:': '🦐',
  ':lobster:': '🦞',
  ':crab:': '🦀',
  ':blowfish:': '🐡',
  ':sushi:': '🍣',
  ':fried_shrimp:': '🍤',
  ':rice_ball:': '🍙',
  ':rice:': '🍚',
  ':rice_cracker:': '🍘',
  ':oden:': '🍢',
  ':dango:': '🍡',
  ':shaved_ice:': '🍧',
  ':ice_cream:': '🍦',
  ':icecream:': '🍨',
  ':cake:': '🍰',
  ':birthday:': '🎂',
  ':cupcake:': '🧁',
  ':pie:': '🥧',
  ':chocolate_bar:': '🍫',
  ':candy:': '🍬',
  ':lollipop:': '🍭',
  ':custard:': '🍮',
  ':doughnut:': '🍩',
  ':cookie:': '🍪',
  ':milk_glass:': '🥛',
  ':beer:': '🍺',
  ':beers:': '🍻',
  ':clinking_glasses:': '🥂',
  ':wine_glass:': '🍷',
  ':tumbler_glass:': '🥃',
  ':cocktail:': '🍸',
  ':tropical_drink:': '🍹',
  ':champagne:': '🍾',
  ':sake:': '🍶',
  ':tea:': '🍵',
  ':coffee:': '☕',
  ':baby_bottle:': '🍼',
  
  // 動物
  ':dog:': '🐶',
  ':cat:': '🐱',
  ':mouse:': '🐭',
  ':hamster:': '🐹',
  ':rabbit:': '🐰',
  ':fox_face:': '🦊',
  ':bear:': '🐻',
  ':panda_face:': '🐼',
  ':koala:': '🐨',
  ':tiger:': '🐯',
  ':lion:': '🦁',
  ':cow:': '🐮',
  ':pig:': '🐷',
  ':pig_nose:': '🐽',
  ':frog:': '🐸',
  ':squid:': '🦑',
  ':octopus:': '🐙',
  ':monkey_face:': '🐵',
  ':gorilla:': '🦍',
  ':see_no_evil:': '🙈',
  ':hear_no_evil:': '🙉',
  ':speak_no_evil:': '🙊',
  ':monkey:': '🐒',
  ':chicken:': '🐔',
  ':penguin:': '🐧',
  ':bird:': '🐦',
  ':baby_chick:': '🐤',
  ':hatching_chick:': '🐣',
  ':hatched_chick:': '🐥',
  ':duck:': '🦆',
  ':eagle:': '🦅',
  ':owl:': '🦉',
  ':bat:': '🦇',
  ':wolf:': '🐺',
  ':boar:': '🐗',
  ':horse:': '🐴',
  ':unicorn:': '🦄',
  ':honeybee:': '🐝',
  ':bug:': '🐛',
  ':butterfly:': '🦋',
  ':snail:': '🐌',
  ':beetle:': '🐞',
  ':ant:': '🐜',
  ':grasshopper:': '🦗',
  ':spider:': '🕷️',
  ':scorpion:': '🦂',
  ':snake:': '🐍',
  ':lizard:': '🦎',
  ':t-rex:': '🦖',
  ':sauropod:': '🦕',
  ':turtle:': '🐢',
  ':tropical_fish:': '🐠',
  ':shark:': '🦈',
  ':dolphin:': '🐬',
  ':whale:': '🐳',
  ':whale2:': '🐋',
  ':crocodile:': '🐊',
  ':leopard:': '🐆',
  ':zebra:': '🦓',
  ':orangutan:': '🦧',
  ':elephant:': '🐘',
  ':mammoth:': '🦣',
  ':bison:': '🦬',
  ':hippopotamus:': '🦛',
  ':rhino:': '🦏',
  ':dromedary_camel:': '🐪',
  ':camel:': '🐫',
  ':giraffe:': '🦒',
  ':kangaroo:': '🦘',
  ':llama:': '🦙',
  ':otter:': '🦦',
  ':sloth:': '🦥',
  ':badger:': '🦡',
  ':feet:': '🐾',
  
  // 自然和天氣
  ':sun:': '☀️',
  ':partly_sunny:': '⛅',
  ':cloud:': '☁️',
  ':sun_behind_rain_cloud:': '🌦️',
  ':thunder_cloud_and_rain:': '⛈️',
  ':zap:': '⚡',
  ':snowflake:': '❄️',
  ':snowman:': '☃️',
  ':snowman_with_snow:': '⛄',
  ':comet:': '☄️',
  ':ocean:': '🌊',
  
  // 地點和建築
  ':house:': '🏠',
  ':house_with_garden:': '🏡',
  ':derelict_house:': '🏚️',
  ':office:': '🏢',
  ':department_store:': '🏬',
  ':post_office:': '🏣',
  ':european_post_office:': '🏤',
  ':hospital:': '🏥',
  ':bank:': '🏦',
  ':hotel:': '🏨',
  ':convenience_store:': '🏪',
  ':school:': '🏫',
  ':love_hotel:': '🏩',
  ':wedding:': '💒',
  ':classical_building:': '🏛️',
  ':church:': '⛪',
  ':mosque:': '🕌',
  ':hindu_temple:': '🛕',
  ':synagogue:': '🕍',
  ':shinto_shrine:': '⛩️',
  ':kaaba:': '🕋',
  
  // 活動和慶祝
  ':tada:': '🎉',
  ':confetti_ball:': '🎊',
  ':balloon:': '🎈',
  ':gift:': '🎁',
  ':ribbon:': '🎀',
  ':wrapped_gift:': '🎁',
  ':jack_o_lantern:': '🎃',
  ':christmas_tree:': '🎄',
  ':fireworks:': '🎆',
  ':sparkler:': '🎇',
  ':sparkles:': '✨',
  ':eight_spoked_asterisk:': '✳️',
  ':eight_pointed_black_star:': '✴️',
  ':sparkle:': '❇️',
  ':o:': '⭕',
  ':hotsprings:': '♨️',
  ':no_entry:': '⛔',
  ':name_badge:': '📛',
  ':no_entry_sign:': '🚫',
  ':100:': '💯',
  ':no_pedestrians:': '🚷',
  ':do_not_litter:': '🚯',
  ':no_bicycles:': '🚳',
  ':non-potable_water:': '🚱',
  ':underage:': '🔞',
  ':no_mobile_phones:': '📵',
  ':low_brightness:': '🔅',
  ':high_brightness:': '🔆',
  ':fleur_de_lis:': '⚜️',
  ':children_crossing:': '🚸',
  ':beginner:': '🔰',
  ':recycle:': '♻️',
  ':u6307:': '🈯',
  ':chart:': '💹',
  ':diamond_shape_with_a_dot_inside:': '💠',
  ':cyclone:': '🌀',
  ':loop:': '➿',
  ':globe_with_meridians:': '🌐',
  ':m:': 'Ⓜ️',
  ':atm:': '🏧',
  ':sa:': '🈂️',
  ':passport_control:': '🛂',
  ':customs:': '🛃',
  ':baggage_claim:': '🛄',
  ':left_luggage:': '🛅',
  ':wheelchair:': '♿',
  ':no_smoking:': '🚭',
  ':wc:': '🚾',
  ':parking:': '🅿️',
  ':potable_water:': '🚰',
  ':mens:': '🚹',
  ':womens:': '🚺',
  ':baby_symbol:': '🚼',
  ':restroom:': '🚻',
  ':put_litter_in_its_place:': '🚮',
  ':cinema:': '🎦',
  ':signal_strength:': '📶',
  ':koko:': '🈁',
  ':ng:': '🆖',
  ':ok:': '🆗',
  ':up:': '🆙',
  ':cool:': '🆒',
  ':new:': '🆕',
  ':free:': '🆓',
  ':zero:': '0️⃣',
  ':one:': '1️⃣',
  ':two:': '2️⃣',
  ':three:': '3️⃣',
  ':four:': '4️⃣',
  ':five:': '5️⃣',
  ':six:': '6️⃣',
  ':seven:': '7️⃣',
  ':eight:': '8️⃣',
  ':nine:': '9️⃣',
  ':keycap_ten:': '🔟',
  ':1234:': '🔢',
  ':hash:': '#️⃣',
  ':asterisk:': '*️⃣',
  ':eject_button:': '⏏️',
  ':arrow_forward:': '▶️',
  ':pause_button:': '⏸️',
  ':next_track_button:': '⏭️',
  ':stop_button:': '⏹️',
  ':record_button:': '⏺️',
  ':play_or_pause_button:': '⏯️',
  ':previous_track_button:': '⏮️',
  ':fast_forward:': '⏩',
  ':rewind:': '⏪',
  ':twisted_rightwards_arrows:': '🔀',
  ':repeat:': '🔁',
  ':repeat_one:': '🔂',
  ':arrow_backward:': '◀️',
  ':arrow_up_small:': '🔼',
  ':arrow_down_small:': '🔽',
  ':arrow_double_up:': '⏫',
  ':arrow_double_down:': '⏬',
  ':arrow_right:': '➡️',
  ':arrow_left:': '⬅️',
  ':arrow_up:': '⬆️',
  ':arrow_down:': '⬇️',
  ':arrow_upper_right:': '↗️',
  ':arrow_lower_right:': '↘️',
  ':arrow_lower_left:': '↙️',
  ':arrow_upper_left:': '↖️',
  ':arrow_up_down:': '↕️',
  ':left_right_arrow:': '↔️',
  ':arrows_counterclockwise:': '🔄',
  ':arrow_right_hook:': '↪️',
  ':leftwards_arrow_with_hook:': '↩️',
  ':arrow_heading_up:': '⤴️',
  ':arrow_heading_down:': '⤵️',
  ':abc:': '🔤',
  ':abcd:': '🔡',
  ':capital_abcd:': '🔠',
  ':symbols:': '🔣',
  ':musical_note:': '🎵',
  ':notes:': '🎶',
  ':arrows_clockwise:': '🔃',
  ':heavy_dollar_sign:': '💲',
  ':currency_exchange:': '💱',
  ':copyright:': '©️',
  ':registered:': '®️',
  ':tm:': '™️',
  ':end:': '🔚',
  ':back:': '🔙',
  ':on:': '🔛',
  ':top:': '🔝',
  ':soon:': '🔜',
  ':white_circle:': '⚪',
  ':black_circle:': '⚫',
  ':red_circle:': '🔴',
  ':large_blue_circle:': '🔵',
  ':small_orange_diamond:': '🔸',
  ':small_blue_diamond:': '🔹',
  ':large_orange_diamond:': '🔶',
  ':large_blue_diamond:': '🔷',
  ':small_red_triangle:': '🔺',
  ':black_small_square:': '▪️',
  ':white_small_square:': '▫️',
  ':black_large_square:': '⬛',
  ':white_large_square:': '⬜',
  ':small_red_triangle_down:': '🔻',
  ':black_medium_square:': '◼️',
  ':white_medium_square:': '◻️',
  ':black_medium_small_square:': '◾',
  ':white_medium_small_square:': '◽',
  ':black_square_button:': '🔲',
  ':white_square_button:': '🔳',
  ':speaker:': '🔈',
  ':sound:': '🔉',
  ':loud_sound:': '🔊',
  ':mute:': '🔇',
  ':mega:': '📣',
  ':loudspeaker:': '📢',
  ':bell:': '🔔',
  ':no_bell:': '🔕',
  ':black_joker:': '🃏',
  ':mahjong:': '🀄',
  ':spades:': '♠️',
  ':clubs:': '♣️',
  ':hearts:': '♥️',
  ':diamonds:': '♦️',
  ':flower_playing_cards:': '🎴',
  ':thought_balloon:': '💭',
  ':right_anger_bubble:': '🗯️',
  ':speech_balloon:': '💬',
  ':left_speech_bubble:': '🗨️',
  ':clock1:': '🕐',
  ':clock2:': '🕑',
  ':clock3:': '🕒',
  ':clock4:': '🕓',
  ':clock5:': '🕔',
  ':clock6:': '🕕',
  ':clock7:': '🕖',
  ':clock8:': '🕗',
  ':clock9:': '🕘',
  ':clock10:': '🕙',
  ':clock11:': '🕚',
  ':clock12:': '🕛',
  ':clock130:': '🕜',
  ':clock230:': '🕝',
  ':clock330:': '🕞',
  ':clock430:': '🕟',
  ':clock530:': '🕠',
  ':clock630:': '🕡',
  ':clock730:': '🕢',
  ':clock830:': '🕣',
  ':clock930:': '🕤',
  ':clock1030:': '🕥',
  ':clock1130:': '🕦',
  ':clock1230:': '🕧'
}

// 轉換 emoji 的主函數
export const convertEmojis = (text) => {
  let result = text
  
  // 按長度排序，確保較長的 emoji 代碼先被處理
  const sortedEmojiEntries = Object.entries(emojiMap).sort((a, b) => b[0].length - a[0].length)
  
  sortedEmojiEntries.forEach(([code, emoji]) => {
    // 轉義特殊字符以用於正則表達式
    const escapedCode = code.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const regex = new RegExp(escapedCode, 'g')
    result = result.replace(regex, emoji)
  })
  
  return result
}

// 檢查文本是否包含 emoji 代碼
export const hasEmojiCodes = (text) => {
  return Object.keys(emojiMap).some(code => text.includes(code))
}

// 獲取所有支援的 emoji 代碼列表
export const getSupportedEmojiCodes = () => {
  return Object.keys(emojiMap).sort()
}

// 搜尋 emoji
export const searchEmojis = (query) => {
  const lowerQuery = query.toLowerCase()
  return Object.entries(emojiMap).filter(([code]) => 
    code.toLowerCase().includes(lowerQuery)
  )
}

export default {
  emojiMap,
  convertEmojis,
  hasEmojiCodes,
  getSupportedEmojiCodes,
  searchEmojis
} 